export const CHANGE_FILTER = 'CHANGE_FILTER';

export const ADD_TO_CART = 'ADD_TO_CART';
export const DELETE_CART_ITEM = 'DELETE_CART_ITEM';
export const CHANGE_QUANTITY_CART_ITEM = 'CHANGE_QUANTITY_CART_ITEM';
